

export const GET_EXPENSE_START = 'GET_EXPENSE_START'
export const GET_EXPENSE_SUCCESS = 'GET_EXPENSE_SUCCESS'
export const GET_EXPENSE_FAILED = 'GET_EXPENSE_FAILED'

export const ADD_EXPENSE_START = "ADD_EXPENSE_START"
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS"
export const ADD_EXPENSE_FAILED = "ADD_EXPENSE_FAILED"
export const ADD_EXPENSE = "APP_EXPENSE";

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT'

export const CHECK_AUTH_STATUS = 'CHECK_AUTH_STATUS';

export const GET_QUOTE = 'GET_QUOTE';

export const GET_LOCATION = 'GET_LOCATION';

export const GET_TASK = 'GET_TASK'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'
export const GET_TASK_FAILED = 'GET_TASK_FAILED'

export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"
export const ADD_TASK_FAILED = "ADD_TASK_FAILED"
export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';