

export const GET_EXPENSE_START = 'GET_EXPENSE_START'
export const GET_EXPENSE_SUCCESS = 'GET_EXPENSE_SUCCESS'
export const GET_EXPENSE_FAILED = 'GET_EXPENSE_FAILED'

export const ADD_EXPENSE_START = "ADD_EXPENSE_START"
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS"
export const ADD_EXPENSE_FAILED = "ADD_EXPENSE_FAILED"
export const ADD_EXPENSE = "APP_EXPENSE";